plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'app.swipego.lcbconnect'
    compileSdk 34

    defaultConfig {
        applicationId "app.swipego.lcbconnect"
        minSdk 24
        targetSdk 34
        versionCode 3
        versionName "1.2.0"
    }

    signingConfigs {
        release {
            storeFile file("../keystore.jks")
            storePassword "lcbconnect2026"
            keyAlias "lcbconnect"
            keyPassword "lcbconnect2026"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'androidx.core:core:1.13.1'
}
